const data=[
 {title:"Обучение RKO",children:[{title:"Как устроена модель",children:[{title:"Что такое RKO",body:"В демонстрационной версии здесь находится пример урока. В полноценной платформе материал будет состоять из текста, изображений, видео, аудио и прикреплённых файлов."},{title:"Откуда берутся выплаты",body:"Пример страницы урока о работе партнёрской модели и последовательности действий ученика."}]},{title:"Партнёрские программы",children:[{title:"Регистрация и начало работы",body:"Здесь будет пошаговый материал по взаимодействию с партнёрскими программами."}]}]},
 {title:"Скрипты",children:[{title:"Первый диалог",children:[{title:"Начало общения",body:"Пример скрипта: структура первого сообщения, вопросы и плавный переход к дальнейшему разговору."}]},{title:"Созвон",children:[{title:"Структура созвона",body:"Пример материала о подготовке, выявлении ситуации и завершении разговора."}]}]},
 {title:"База знаний",children:[{title:"Полезные материалы",children:[{title:"Подборка статей",body:"Здесь будут собраны полезные статьи, видео и дополнительные материалы по работе."}]},{title:"ИИ в работе",children:[{title:"Практическое применение",body:"Пример урока об использовании искусственного интеллекта для текстов, анализа и подготовки материалов."}]}]},
 {title:"Инструменты",children:[{title:"Шаблоны и таблицы",children:[{title:"Рабочие материалы",body:"В этом разделе будут находиться шаблоны, таблицы, чек-листы и файлы для скачивания."}]}]}
];
const $=s=>document.querySelector(s);const screens=[$("#loginScreen"),$("#welcomeScreen"),$("#dashboardScreen"),$("#noAdmin")];let path=[];let timer;
function screen(active){screens.forEach(s=>s.classList.toggle("is-active",s===active))}
setTimeout(()=>$("#splash").classList.add("is-gone"),2200);
$("#eye").onclick=()=>{const p=$("#password");p.type=p.type==="password"?"text":"password"};
$("#loginForm").onsubmit=e=>{e.preventDefault();if(!$("#login").value.trim()||!$("#password").value)return; e.currentTarget.classList.add("is-success");setTimeout(()=>{screen($("#welcomeScreen"));setTimeout(()=>{screen($("#dashboardScreen"));render()},1050)},700)};
function items(){let a=data;for(const i of path)a=a[i].children||[];return a}
function render(){const list=$("#list");list.innerHTML="";$("#article").classList.remove("is-visible");list.style.display="block";$("#pageTitle").style.display="block";$(".guide").style.display="flex";$("#back").classList.toggle("is-visible",path.length>0);$("#guide").textContent=path.length===0?"ВЫБЕРИ РАЗДЕЛ, ЧТОБЫ ПОСМОТРЕТЬ ДЕМОНСТРАЦИЮ.":path.length===1?"ВЫБЕРИ МОДУЛЬ, ЧТОБЫ ПЕРЕЙТИ К МАТЕРИАЛАМ.":"ВЫБЕРИ МАТЕРИАЛ, ЧТОБЫ ОТКРЫТЬ ЕГО.";items().forEach((x,i)=>{const b=document.createElement("button");b.className="row";b.innerHTML=`<span>[${String(i+1).padStart(2,"0")}]</span><strong></strong><b></b><em>→</em>`;b.querySelector("strong").textContent=x.title;b.onclick=()=>{if(x.children){path.push(i);render()}else article(x)};list.appendChild(b)})}
function article(x){$("#list").style.display="none";$("#pageTitle").style.display="none";$(".guide").style.display="none";const a=$("#article");a.classList.add("is-visible");$("#articlePath").textContent=path.map((idx,n)=>{let arr=data;for(let j=0;j<n;j++)arr=arr[path[j]].children;return arr[idx].title}).join("  /  ");$("#articleTitle").textContent=x.title;$("#articleBody").textContent=x.body}
$("#back").onclick=()=>{path.pop();render()};$("#articleBack").onclick=render;
$("#admin").onclick=()=>{screen($("#noAdmin"));setTimeout(()=>screen($("#dashboardScreen")),1300)};
$("#logout").onclick=()=>{path=[];$("#loginForm").reset();$("#loginForm").classList.remove("is-success");screen($("#loginScreen"))};
